### PR TITLE
Fix Spotify embeds

### PR DESCRIPTION
**Pull request by lewispb**
Spotify are returning a relative path for the redirect. I've added a test and updated the HTTP helper to support this.

### CODE REVIEW

**Review by metavida — CHANGES_REQUESTED** [review]
Thanks so much for this PR! Unfortunately it seems like it currently breaks quite a few tests: https://github.com/ruby-oembed/ruby-oembed/actions/runs/8040827022/job/21959367990?pr=95

ruby-oembed@3899243 2024-02-25 13-20-43

For some reason this specific PR failed to trigger my GitHub Actions based CI tests but I've confirmed the failing tests locally & also opened a duplicate PR (https://github.com/ruby-oembed/ruby-oembed/pull/95) that helped confirm that the failing tests aren't specific to me. Maybe closing & re-opening the PR would somehow trigger the CI?

I don't have time to try and debug the failures at the moment, but will keep a follow-up investigation on my TODO list.

**Comment by ipatovanton** [comment]
any updates?

**Comment by metavida** [comment]
Oh no! Somehow this fell off my list. Thanks so much for the nudge so I can move it back up to the top.

**Comment by metavida** [comment]
At **long** last I had time to get this fix merged and released https://rubygems.org/gems/ruby-oembed/versions/0.18.1

And PR #95 has additional improvements to the built-in Spotify provider including switching to [the officially documebnted Spotify oEmbed API endpoint](https://developer.spotify.com/documentation/embeds/reference/oembed).

Thanks again for bringing this bug to my attention & helping move towards a fix!

**Pull request merged**
