### PR TITLE
Reduce gem size

### PR DESCRIPTION
**Pull request by fauno**
I was doing cleanup and noticed ruby-oembed gem was ~18MB, mostly because of `spec/cassettes/OEmbed_ProviderDiscovery.yml`.

### CODE REVIEW

**Review by metavida — APPROVED** [review]
Makes sense! And thanks to the links to the relevant conversations so I could learn more about the deprecation/abandonment of the `test_files` config. I think I'll have time for a new point release over the next 2ish days. 

If you have time one thing that still needs to be done before the new release is adding a line to the CHANGELOG. If you've got time to add to the CHANGELOG via this PR go for it! And if I get time first then I'll add to the CHANGELOG after merging this PR.

Thanks for your help improving this gem!

**Comment by fauno** [comment]
Done! :D

**Comment by metavida** [comment]
Just pushed version 0.16.0 to rubygems, which includes the changes from this PR! Thanks for helping make ruby-oembed better!

**Comment by fauno** [comment]
Great!  Thanks!  Just released jekyll-embed-urls v0.4.4 to reflect this :)

https://rubygems.org/gems/jekyll-embed-urls

**Pull request merged**
